### ISSUE TITLE
Parse out namespace from a file

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#1]
We have a **Evaluate selection** command to compensate a bit for the current lack of an nREPL server. However to evaluate a piece of code we need to do it in the right namespace, which is a bit clunky right now.

https://user-images.githubusercontent.com/30010/165396458-37c80b72-7acd-4635-9ef4-367378fe4f9b.mp4

With a way to parse out the namespace from the current file we could make this much more convenient.

Ping @borkdude

**Comment by borkdude** [comment]
Obsoleted by nREPL
