### ISSUE TITLE
A command for evaluating the selection 

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#106]
Calva is limited to one REPL session per window. Meaning that if you work with a Clojure project and have Calva connected to the project REPL, you can't also be connected to Joyride's REPL. In waiting for this to be solved in Calva, Joyride can make it more convenient to evaluate code by allowing the selection to be evaluated conveniently.

The user can solve this with Joyride, but it is a worthy command to have built in.

**Comment by PEZ** [comment]
I should be banned from late coding, @borkdude. Pushed the commit directly to master, but had intended to make it a pull request. Please have a look at the commit.

**Comment by borkdude** [comment]
I trust that you did what you needed to do ;-). I'm not sure if the code will be evaluated in the right namespace using this approach

**Comment by PEZ** [comment]
Good point! We should already have that problem with the current runCode command. But the user expectations might be different, of course.

I'll try to figure out what namespace it is evaluated in.
