### ISSUE TITLE
Add `src` sub User and Workspace directories to the classpath

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#115]
I think that for me most of my source files are not scripts. Yet Joyride enumerates all files as if they were scripts. If Joyride has some other directories in its classpath the `joyride/scripts` directories could contain only scripts and other source files could be placed outside.

Since tools/deps adds `src` to the classpath by default, we could add `<ws-root>/.joyride/src` and `<home>/.config/joyride/src` by default. And defer making this a configuration thing.

**Comment by borkdude** [comment]
Sound good
