### ISSUE TITLE
Error `No context found` when evaluating `is` form

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#124]
I can't evaluate `is` forms.  Here's a minimal example:

`<user-config>/joyride/src/cljs-test.cljs`:

```clojure
(ns cljs-test
  (:require [cljs.test :refer [deftest is testing]]))

(deftest foo
  (testing "foo"
    (is (= 1 2))))
```

Evaluating the `ns` form works fine, but evaluating the  `is` form I get:

```
; No context found in: sci.ctx-store/*ctx*. Please set it using sci.ctx-store/reset-ctx!
```

Evaluating the `deftest` form without the `is` also works.

**Comment by borkdude** [comment]
@PEZ Follow the error message and do this:

https://github.com/babashka/nbb/blob/6a9b6757132092016f92c3c0a4bcecc85a522f4e/src/nbb/core.cljs#L532

The sci.config for cljs.test expects the context in a specific location so it can access it.

**Comment by PEZ** [comment]
Thanks, @borkdude, that works great. PR coming up.
