### ISSUE TITLE
404 links in documentation

### ISSUE THREAD

**Issue by alpox** [BetterThanTomorrow/joyride#162]
At https://github.com/BetterThanTomorrow/joyride/tree/master/examples#lookup-current-symbol-in-clojuredocs there is the link [.joyride/scripts/clojuredocs.cljs](https://github.com/BetterThanTomorrow/joyride/blob/master/examples/.joyride/scripts/clojuredocs.cljs)

And under https://github.com/BetterThanTomorrow/joyride/tree/master/examples#user_activatecljs the link [activate.cljs](https://github.com/BetterThanTomorrow/joyride/blob/master/assets/getting-started-content/user/activate.cljs)

But they are leading into nowhere. Likely the assets were removed at some point.

**Comment by PEZ** [comment]
Thanks! Now fixed.
