### ISSUE TITLE
Bump version of promesa

### ISSUE THREAD

**Issue by YizhePKU** [BetterThanTomorrow/joyride#163]
Some functions, such as `p/extract`, is not available in the currently used version of promesa (it is only defined for Clojure, not for ClojureScript). Bumping version to latest should be a good idea.

**Comment by YizhePKU** [comment]
Edit: now that I look at the documentation of promesa 9.0.471, it does say that `p/extract` is supported on both Clojure and ClojureScript. For some reason, this is changed on 9.0.477. Still, I can't find `p/extract` in my repl, which confuses me.

**Comment by borkdude** [comment]
You need to add it here: https://github.com/babashka/sci.configs/blob/d0ef6083fdfac86dc3dd8948918acde334442405/src/sci/configs/funcool/promesa.cljs#L162

and then you need to bump sci.configs in this project
