### ISSUE TITLE
Unwanted .joyride directory creation.

### ISSUE THREAD

**Issue by dionysus98** [BetterThanTomorrow/joyride#174]
A new `.joyride` directory is being created at the start of editor on every project. 
**note**: This happens even on *non clojure* projects.

Joyride version: `v0.0.36`
calva version: `v2.0.398`
Vscode version: `v1.84.2`
system OS: Linux x64

**Comment by PEZ** [comment]
Thanks. That wasn't really intended. I'll have a look at what we could do about that.

**Comment by PEZ** [comment]
Should be fixed in v0.0.37, @dionysus98.

> **note**: This happens even on _non clojure_ projects.

Joyride is not a Clojure project tool, really, just sayn' 😄

**Comment by dionysus98** [comment]
Thanks c: @PEZ 
And yes I apologise, I did look at the docs after I wrote this issue.  :laughing:
