### ISSUE TITLE
Joyride Run Script prompt placeholder code does not work

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#19]
The *Joyride Run Script* command brings up a prompt with this placeholder text: `(require '[\"path\" :as path]) (path/resolve \".\")`.

However, entering that code gives this message:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/30010/166152808-e13c5714-fc99-45f1-8231-de9bc5a0c6e5.png">

**Comment by borkdude** [comment]
It's not a bug in the evaluation but a bug in the placeholder text, the quotes should not be escaped.

**Comment by borkdude** [comment]
I think we should just put `(+ 1 2 3)` there or so.

**Comment by PEZ** [comment]
Ah, yes, it was me forgetting to `println` it before I copied. =)
