### ISSUE TITLE
Don't automatically show the Joyride output channel when scripts run

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#36]
Currently when a script is run, we show the Joyride output channel automatically without any way to prevent it. It would be good if this could be optional on a per script basis.

**Comment by PEZ** [comment]
I think a way to solve it is to add an API for showing the panel. Then a script can choose to do so at any point in the execution. And we won't need to add configuration for it.

**Comment by orestis** [comment]
Yes please :)
