### ISSUE TITLE
Don't unconditionally show the Joyride output channel on start

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#46]
Device some way to opt out of the Joyride message/output channel showing at startup.

**Comment by borkdude** [comment]
Opt out? I would say that by default an output channel should not steal focus (I also don't like that Calva does that).

**Comment by PEZ** [comment]
Opt out. It's my experience with Calva that it is a good thing for many new users to get some basic information and know where to look for it. Most do not opt out of it, but they can.

**Comment by borkdude** [comment]
I think it's an unnecessary form of attention seeking and I've seen more users complain about this in the joyride channel ;-).
