### ISSUE TITLE
*file* is not being set

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#5]
The `*file*` variable is not yet set by Joyride when running scripts.

**Comment by borkdude** [comment]
In CLJS there is no `*file*`. Using `*file*` without a namespace context in CLJS will give a warning in clj-kondo. Therefore I opted in nbb to create a separate namespace `nbb.core` with `*file*` dynamic var in it. I propose we do the same in joyride:

```
joyride.core/*file*
```
