### ISSUE TITLE
Create example user scripts if they are not present

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#52]
As a user who has just installed Joyride, it's boring with no content at all. Joyride could create two example scripts so that the new user has something to start playing around with:

- `hello_joyride.cljs` - with some basic VS Code API used, possibly just showing an information message with two buttons, one which takes you to the Joyride examples page.
- `activate.cljs` - which could just show the Joyride output channel and say something in it. Maybe print the paths to the two created files.

**Comment by borkdude** [comment]
Can a user opt out of this? I usually don't like tools polluting my projects if I didn't ask for it. Again, I think this is unnecessary noise.

**Comment by borkdude** [comment]
Sorry, I misunderstood: user scripts, not workspace scripts. All good then.
