### ISSUE TITLE
How to disable the joyride output when vscode launches?

### ISSUE THREAD

**Issue by introom** [BetterThanTomorrow/joyride#65]
When vscode starts, the joyride output will always show up.
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/669045/168796584-714f57e7-e220-40c8-a7af-d3b508bd4744.png">

Is it possible to disable this behavior?

**Comment by borkdude** [comment]
I think it should be disabled by default.

**Comment by PEZ** [comment]
It says how you do it in the screenshot you posted, @introom 😀

**Comment by introom** [comment]
😂.  Right!
