### ISSUE TITLE
User scripts

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#7]
_As a Joyrider I want to have easy access to my non-project-specific scripts so that I can improve VS Code across projects I work with._

Includes

* A menu for user scripts
* Args when binding shortcuts have a same ”relative to <user scripts dir>” context, equivalent to that of workspace scripts

Should namespace resolution consider both these locations as source path roots? I tend to think so. With workspace overriding, so equivalent to:

```clojure
:source-paths ["user" "workspace"]
```

**Comment by borkdude** [comment]
Where do user scripts live, in `~/.config/joyride/scripts`?

**Comment by borkdude** [comment]
We could make the user script directory configurable maybe (but it might be better to wait for that request).

**Comment by PEZ** [comment]
That's why I speculated about the symlinking. If that works, then it is already configurable. =)
