### ISSUE TITLE
Less boilerplate-y require of APIs from VS Code extensions

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#71]
I think it would make sense if extensions can export a "JS library" that can be required from joyride, like any other JS library in the Electron runtime.

``` clojure
(require '["betterthantomorrow.calva$v0" :as calva])
(calva/evaluateCode ...)
```

This reduces boilerplate but also makes it unambiguous from which extension the function is being used. The `$` convention is standard CLJS and also used in nbb. Note that any sub-property of the extension can be selected, so if one would want to export a joyride specific part, one would write: `(require '["betterthantomorrow.calva$v0.joyride" :as calva])`

_Originally posted by @borkdude in https://github.com/BetterThanTomorrow/joyride/discussions/69#discussioncomment-2832412_

**Comment by borkdude** [comment]
One thing to watch here is conflicts between library names and extension names. E.g. if you there will be an NPM library with `betterthantomorrow.calva` in the future, we have to choose if we load the extension of the npm library. It seems unlikely but potentially could be an issue?

**Comment by PEZ** [comment]
Tricky. Should we prefix it? `joyride.betterthantomorrow.calva`, or something.

**Comment by PEZ** [comment]
Or, since npm package names must not start with a dot: `.betterthantomorrow.calva`.
