### ISSUE TITLE
Calva eval/load current file makes cljs.user to be the active ns

### ISSUE THREAD

**Issue by pinkfrog9** [BetterThanTomorrow/joyride#79]
When you eval/load current file, the active ns becomes cljs.user.

The tutorial video also shows this:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/107285219/177238818-d634c258-12dd-433b-b758-8c9903e75fab.png">

**Comment by PEZ** [comment]
Thanks for reporting! This looks like a regression.

**Comment by PEZ** [comment]
It probably is a glitch in when we updated the prompt:

```clojure
cljs꞉user꞉> 
*ns*
#object [w2 hello-joyride-user-script]
cljs꞉hello-joyride-user-script꞉> 
```

**Comment by PEZ** [comment]
We fixed this in Calva.
