### ISSUE TITLE
Activation scripts

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/joyride#8]
_As a Joyrider I want to specify certain scripts to run when Joyride starts so that I can have a predictable startup baseline w/o having to manually run certain scripts in certain order._

This could be configurable in some different ways:

* Two scripts: user and workspace
* Two lists of scripts: user and workspace
* A map: specifies both user and workspace lists of configs with some more richness than a mere script name. We would merge the maps in user-then-workspace setting order
* ...

In all those cases it is important to keep in mind that in VS Code these settings can be specified in both **User** and **Workspace**, which adds configurability, but also is a Ux concern.

These scripts should get Joyride's extension context as one of their arguments.

There is also the option to use some file naming. convention. But I think I want explicit configs here. I lean towards the richer map alternative. At least I want to start with designing such an API and see if it seems nice and flexible enough.

Side note: Another feature idea is deactivation scripts.

**Comment by borkdude** [comment]
I would say this depends on #7 to be solved first. Another alternative may be to have a convention `init.cljs` in your workspace or user script dir that is automatically picked up.

**Comment by nixin72** [comment]
I would personally prefer an entry point on startup like an `init.cljs` over a config file. Feels more appropriate here imo.
