### ISSUE TITLE
Is it possible to include rewrite-clj? Or a clear example on how to rewrite code?

### ISSUE THREAD

**Issue by jwhitlark** [BetterThanTomorrow/joyride#83]
This is already a game changer.  

I frequently use rewrite-clj to update small bits of code.  It's pretty awkward at the moment.  Being able to script small transformations in joyride would be incredibly useful.  Is there some way to accomplish this?  I'm not familiar enough with sci to tell.

**Comment by jwhitlark** [comment]
It looks like it would be possible via calva's extension api, then evaluating it in the repl, then putting the output back into the document.  Suggestions? A better way?

**Comment by jwhitlark** [comment]
This pretty much does what I want.  Putting it here for reference.  Are there any recommended improvements?  It seems like it would be a common pattern.

``` clojure
(ns rewrite
  (:require ["ext://betterthantomorrow.calva$v0.repl" :refer [evaluateCode]]
            ["vscode" :as vscode]
            [joyride.core :as joyride]
            [promesa.core :as p]
            [z-joylib.editor-utils :as eu]))

(defn rewrite [code]
  (str "(clojure.string/upper-case \"" code  "\")"))

(defn main []
  (-> (p/let [editor ^js vscode/window.activeTextEditor
              _ (vscode/commands.executeCommand "calva.selectCurrentForm")
              selection (eu/current-selection)
              code (rewrite (eu/current-selection-text))
              resp (evaluateCode "clj" code)
              raw-out (.-result resp)
              out (subs raw-out 1 (dec (count raw-out)))]
        (eu/delete-range! editor selection)
        (eu/insert-text!+ out editor (.-active selection)))))


(when (= (joyride/invoked-script) joyride/*file*)
  (main))
```

**Comment by jwhitlark** [comment]
Please feel free to close this.

**Comment by PEZ** [comment]
Hi there! Sorry for no answer at all. I've been on vacation.

Can you start this as a Discussion instead of this issue, please? It might be that we want to open an issue for it once we've figured out the use cases, but Discussions is a better place for ironing things out.

That said, this does look very interesting. Both the general pattern and your current solution.

**Comment by jwhitlark** [comment]
Moved to https://github.com/BetterThanTomorrow/joyride/discussions/88
