### ISSUE TITLE
Joyride starts Calva even when not in a Clojure(script) workspace

### ISSUE THREAD

**Issue by danielkarch** [BetterThanTomorrow/joyride#84]
Hi, I noticed that Calva is starting every time I open up VS Code, even when I open it in an empty directory. This only happens when Joyride is also enabled and I believe it happens in [user_activate.cljs](https://github.com/BetterThanTomorrow/joyride/blob/e61a87d61bde0ab9e011dca38c165ee698119f48/assets/getting-started-content/user/user_activate.cljs#L87).
It appears that this has been fixed on `master` (see the [addition in line 92](https://github.com/BetterThanTomorrow/joyride/commit/5413a79ea9e58c0df28457475cbb6b8fc157028c#diff-fd50b3b9a8e51d9413eaffda7413c2593f86873224817e9cdefd79f582599d1cR92)), but is an issue in the latest published version, `v0.0.15`. It would be nice if you could prepare a new release soon. For the time being this can be worked around by manually editing the `user_activate.cljs` file.

**Comment by PEZ** [comment]
Thanks. I had totally missed to also release that change... Releasing v0.0.16 now.
